apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adp-dr-test67
  description: adp-dr-test67
  annotations:
    github.com/project-slug: defra-adp-sandpit/adp-dr-test67
    dev.azure.com/project: DEFRA-ADP
    dev.azure.com/build-definition: adp-dr-test67
    sonarqube.org/project-key: adp-dr-test67
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
    backstage.io/kubernetes-id: adp-dr-test67
  links:
    - url: https://github.com/defra-adp-sandpit/adp-dr-test67
      title: GitHub Repository
      icon: github
    - url: https://dev.azure.com/defragovuk/DEFRA-ADP/
      title: Azure DevOps Project
      icon: project
    - url: https://sonarcloud.io/project/overview?id=adp-dr-test67
      title: SonarCloud Analysis
      icon: check
    - url: https://snyk.io/test/github/DEFRA/adp-dr-test67
      title: Snyk Analysis
      icon: policy
    - url: https://portal.azure.com/defradev.onmicrosoft.com
      title: Azure Portal - Defra Dev
      icon: cloud
    - url: https://portal.azure.com/Defra.onmicrosoft.com
      title: Azure Portal - Defra
      icon: cloud
    - url: https://adp-dr-test67.snd3.adp.defra.gov.uk/
      title: SND3
    - url: https://adp-dr-test67.dev1.adp.defra.gov.uk/
      title: DEV1
    - url: https://adp-dr-test67.tst1.adp.defra.gov.uk/
      title: TST1
    - url: https://adp-dr-test67.pre1.adp.defra.gov.uk/
      title: PRE1
spec:
  type: frontend
  lifecycle: alpha
  owner: "group:default/azure-dev-platform-2"
  system: system:default/adp-shared-services
